from __future__ import annotations

import hashlib
import io
import json
import os
import re
import shlex
import tarfile
import tempfile
import urllib.error
import urllib.request
from functools import cache
from importlib.metadata import version as dist_version
from pathlib import Path
from types import ModuleType
from typing import Any, NamedTuple

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

GUARD_DEFINITION = Path("internal") / "wireproto" / "guard.json"
GUARD_LITERALS = (Path("captain_hook") / "guard_literal.py", Path("capt_hook_client") / "guard_literal.py")
GUARD_SHELL = Path("captain_hook") / "guard_literal.sh"
GUARD_HEADER = "# GENERATED by `uv run python hatch_build.py` from internal/wireproto/guard.json.\n"
STATIC_DENY_KIND = "dependency-unavailable"
KEY_OVERRIDES = {"Cpp": "cpp", "Kotlin": "kotlin", "Solidity": "solidity", "Yaml": "yaml"}
NODE_TYPES_SUBDIRS = {"LANGUAGE_TYPESCRIPT": "typescript/", "LANGUAGE_TSX": "tsx/", "LANGUAGE_PHP_ONLY": "php_only/"}
COMMENT_KIND_OVERRIDES: dict[str, dict[str, tuple[str, ...]]] = {}

MATCH_ARM = re.compile(r"(\w+)\s*=>\s*&\[(.*?)\]", re.DOTALL)
QUOTED = re.compile(r'"([^"]*)"')
PARSER_FN = re.compile(r"impl_lang(?:_expando)?!\(\s*(\w+)\s*,\s*(\w+)")
PARSER_CONDITIONAL = re.compile(
    r'pub fn (\w+)\(\)\s*->\s*TSLanguage\s*\{\s*conditional_lang!\(\s*\w+\s*,\s*"([^"]+)"\s*(?:,\s*(\w+)\s*)?\)',
    re.DOTALL,
)
PACKAGE_BLOCK = re.compile(
    r'\[\[package\]\]\s*\nname = "([^"]+)"\nversion = "([^"]+)"(?:\nsource = "[^"]+")?\nchecksum = "([0-9a-f]+)"'
)


class Sources(NamedTuple):
    lock: str
    cargo_toml: str
    lib: str
    parsers: str


class Crate(NamedTuple):
    package: str
    version: str
    sha256: str
    subdir: str


def ast_grep_version() -> str:
    return dist_version("ast-grep-py")


def cache_dir() -> Path:
    root = Path(os.environ.get("XDG_CACHE_HOME") or Path.home() / ".cache")
    return root / "capt-hook-build" / f"ast-grep-py-{ast_grep_version()}"


def fetch(url: str, *, name: str, sha256: str | None = None) -> bytes:
    path = cache_dir() / name
    if path.exists() and (
        (data := path.read_bytes()) and (sha256 is None or hashlib.sha256(data).hexdigest() == sha256)
    ):
        return data
    request = urllib.request.Request(url, headers={"User-Agent": "capt-hook-build (github.com/yasyf/captain-hook)"})
    try:
        with urllib.request.urlopen(request) as response:
            data = response.read()
    except urllib.error.URLError as error:
        raise RuntimeError(
            f"cannot fetch {url}: {error}; warm the build cache at {cache_dir()} with `uv build` while online"
        ) from error
    if sha256 is not None and (actual := hashlib.sha256(data).hexdigest()) != sha256:
        raise RuntimeError(f"checksum mismatch for {url}: expected {sha256}, got {actual}")
    cache_dir().mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=cache_dir(), delete=False) as tmp:
        tmp.write(data)
    os.replace(tmp.name, path)
    return data


@cache
def sdist_source() -> tuple[str, str]:
    payload = json.loads(
        fetch(f"https://pypi.org/pypi/ast-grep-py/{ast_grep_version()}/json", name=f"pypi-{ast_grep_version()}.json")
    )
    for entry in payload["urls"]:
        if entry["packagetype"] == "sdist":
            return entry["url"], entry["digests"]["sha256"]
    raise RuntimeError(f"no sdist in PyPI metadata for ast-grep-py {ast_grep_version()}")


@cache
def sdist_sources() -> Sources:
    url, sha256 = sdist_source()
    data = fetch(url, name=f"ast_grep_py-{ast_grep_version()}.tar.gz", sha256=sha256)
    root = f"ast_grep_py-{ast_grep_version()}"
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as archive:

        def member(name: str) -> str:
            if (handle := archive.extractfile(f"{root}/{name}")) is None:
                raise RuntimeError(f"{name} missing from ast-grep-py sdist")
            return handle.read().decode()

        return Sources(
            lock=member("Cargo.lock"),
            cargo_toml=member("crates/language/Cargo.toml"),
            lib=member("crates/language/src/lib.rs"),
            parsers=member("crates/language/src/parsers.rs"),
        )


def cargo_checksums(lock: str) -> dict[str, tuple[str, str]]:
    return {m.group(1): (m.group(2), m.group(3)) for m in PACKAGE_BLOCK.finditer(lock)}


def parse_aliases(lib: str) -> dict[str, tuple[str, ...]]:
    if (block := re.search(r"impl_aliases!\s*\{(.*?)\n\}", lib, re.DOTALL)) is None:
        raise RuntimeError(f"no `impl_aliases!` block in ast-grep-py {ast_grep_version()} lib.rs")
    return {m.group(1): tuple(QUOTED.findall(m.group(2))) for m in MATCH_ARM.finditer(block.group(1))}


def parse_extensions(lib: str) -> dict[str, tuple[str, ...]]:
    if (block := re.search(r"fn extensions\(.*?\n\}", lib, re.DOTALL)) is None:
        raise RuntimeError(f"no `fn extensions` block in ast-grep-py {ast_grep_version()} lib.rs")
    return {m.group(1): tuple(QUOTED.findall(m.group(2))) for m in MATCH_ARM.finditer(block.group(0))}


def parser_fns(lib: str) -> dict[str, str]:
    return {m.group(1): m.group(2) for m in PARSER_FN.finditer(lib)} | {"Html": "language_html"}


def parser_table(parsers: str) -> dict[str, tuple[str, str | None]]:
    return {m.group(1): (m.group(2), m.group(3)) for m in PARSER_CONDITIONAL.finditer(parsers)}


def dep_packages(cargo_toml: str) -> dict[str, str]:
    return {
        m.group(1): (pkg.group(1) if (pkg := re.search(r'package\s*=\s*"([^"]+)"', m.group(2))) else m.group(1))
        for m in re.finditer(r"^\s*(tree-sitter-[\w-]+)\s*=\s*\{([^}]*)\}", cargo_toml, re.MULTILINE)
    }


def parser_crates(parsers: str, lib: str, cargo_toml: str, checksums: dict[str, tuple[str, str]]) -> dict[str, Crate]:
    table = parser_table(parsers)
    packages = dep_packages(cargo_toml)
    crates = {}
    for variant, func in parser_fns(lib).items():
        dep_key, field = table[func]
        version, sha256 = checksums[packages[dep_key]]
        crates[variant] = Crate(packages[dep_key], version, sha256, "" if field is None else NODE_TYPES_SUBDIRS[field])
    return crates


def lang_keys(aliases: dict[str, tuple[str, ...]]) -> dict[str, str]:
    keys = {}
    for variant, variant_aliases in aliases.items():
        if (key := KEY_OVERRIDES.get(variant) or min(variant_aliases, key=len)) not in variant_aliases:
            raise RuntimeError(f"lang key {key!r} for {variant} is not an upstream alias of {variant_aliases}")
        keys[variant] = key
    return keys


def comment_kinds(nodes: list[dict[str, object]]) -> set[str]:
    by_type = {node["type"]: node for node in nodes}
    named = {kind for kind, node in by_type.items() if node.get("named") and "comment" in kind}
    referenced = {
        child["type"]
        for kind in named
        for group in (*by_type[kind].get("fields", {}).values(), by_type[kind].get("children", {}))
        for child in group.get("types", [])
    }
    return named - referenced


def doc_comment_kinds(nodes: list[dict[str, object]]) -> set[str]:
    named = {node["type"] for node in nodes if node.get("named")}
    return {kind for kind in named if ("marker" in kind and "doc" in kind) or "documentation" in kind}


@cache
def variant_keys() -> dict[str, str]:
    return lang_keys(parse_aliases(sdist_sources().lib))


@cache
def crate_table() -> dict[str, Crate]:
    sources = sdist_sources()
    crates = parser_crates(sources.parsers, sources.lib, sources.cargo_toml, cargo_checksums(sources.lock))
    if missing := sorted(set(parse_aliases(sources.lib)) - set(crates)):
        raise RuntimeError(f"no parser crate resolved for languages: {missing}")
    return crates


def grammar_node_types(crate: Crate) -> list[dict[str, object]]:
    data = fetch(
        f"https://static.crates.io/crates/{crate.package}/{crate.package}-{crate.version}.crate",
        name=f"{crate.package}-{crate.version}.crate",
        sha256=crate.sha256,
    )
    member = f"{crate.package}-{crate.version}/{crate.subdir}src/node-types.json"
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as archive:
        if (handle := archive.extractfile(member)) is None:
            raise RuntimeError(f"{member} missing from {crate.package} {crate.version}")
        return json.load(handle)


@cache
def grammar_inventories() -> dict[str, list[dict[str, object]]]:
    keys = variant_keys()
    return {
        key: grammar_node_types(crate)
        for variant, crate in crate_table().items()
        if (key := keys[variant]) not in frozenset({"md"})
    }


def build_lang_globs(lib: str) -> dict[str, tuple[str, ...]]:
    extensions = parse_extensions(lib)
    keys = lang_keys(parse_aliases(lib))
    if missing := sorted(set(keys) - set(extensions)):
        raise RuntimeError(f"no extensions parsed for languages: {missing!r}")
    owners: dict[str, str] = {}
    for variant, variant_exts in extensions.items():
        for ext in variant_exts:
            if ext in owners:
                raise RuntimeError(f"extension {ext!r} claimed by both {owners[ext]} and {variant}")
            owners[ext] = variant
    return {
        keys[variant]: tuple(sorted(f"*.{ext}" for ext in variant_exts))
        for variant, variant_exts in sorted(extensions.items(), key=lambda item: keys[item[0]])
    }


def build_comment_types() -> frozenset[str]:
    by_lang: dict[str, frozenset[str]] = {}
    for key, nodes in grammar_inventories().items():
        override = COMMENT_KIND_OVERRIDES.get(key, {})
        kinds = comment_kinds(nodes) | set(override.get("add", ()))
        by_lang[key] = frozenset(kinds - set(override.get("remove", ())))
    if empty := sorted(lang for lang, kinds in by_lang.items() if not kinds):
        raise RuntimeError(f"languages define no comment kinds: {empty}")
    return frozenset(kind for kinds in by_lang.values() for kind in kinds)


def build_doc_comment_kinds() -> frozenset[str]:
    kinds = frozenset(kind for nodes in grammar_inventories().values() for kind in doc_comment_kinds(nodes))
    if not kinds >= {"inner_doc_comment_marker", "outer_doc_comment_marker"}:
        raise RuntimeError(f"doc-comment kind derivation collapsed to {sorted(kinds)}; rust's markers are the floor")
    return kinds


def render_langs() -> str:
    globs = build_lang_globs(sdist_sources().lib)
    globs_body = "\n".join(f"    {key!r}: {value!r}," for key, value in globs.items())
    comments_body = "\n".join(f"        {kind!r}," for kind in sorted(build_comment_types()))
    doc_body = "\n".join(f"        {kind!r}," for kind in sorted(build_doc_comment_kinds()))
    return (
        "# GENERATED by `uv run python hatch_build.py`.\n"
        f"# ast-grep-py {ast_grep_version()}.\n\n"
        "from __future__ import annotations\n\n"
        "LANG_GLOBS: dict[str, tuple[str, ...]] = {\n"
        f"{globs_body}\n"
        "}\n\n"
        "COMMENT_TYPES: frozenset[str] = frozenset(\n"
        "    {\n"
        f"{comments_body}\n"
        "    }\n"
        ")\n\n"
        "DOC_COMMENT_KINDS: frozenset[str] = frozenset(\n"
        "    {\n"
        f"{doc_body}\n"
        "    }\n"
        ")\n"
    )


def write_langs(path: Path) -> None:
    path.write_text(render_langs())


def escaped(char: str) -> str:
    return char.replace("\\", "\\\\").replace('"', '\\"')


def literal(value: str) -> str:
    return '"' + "".join(map(escaped, value)) + '"'


def rune_literal(char: str) -> str:
    return f'"\\u{ord(char):04x}"'


def wrapped_literal(value: str, *, width: int = 100) -> str:
    lines: list[str] = [""]
    for char in value:
        if len(lines[-1]) + len(escaped(char)) > width:
            lines.append("")
        lines[-1] += escaped(char)
    if len(lines) == 1:
        return f'"{lines[0]}"'
    return "(\n" + "".join(f'    "{line}"\n' for line in lines) + ")"


def render_guard_literal(definition: dict[str, Any]) -> str:
    events = ", ".join(literal(event) for event in definition["events"])
    folds = ", ".join(f"{rune_literal(source)}: {literal(target)}" for source, target in definition["folds"].items())
    kinds = "".join(f"    {literal(kind)},\n" for kind in definition["kinds"])
    exempt_heads = "".join(f"    {literal(head)},\n" for head in definition["exempt_heads"])
    return (
        f"{GUARD_HEADER}\n"
        "from __future__ import annotations\n\n"
        "import json\n"
        "import os\n"
        "import re\n"
        "import sys\n"
        "from typing import BinaryIO, cast\n\n"
        f"EVENTS: frozenset[str] = frozenset({{{events}}})\n"
        f"QUOTING: str = {wrapped_literal(definition['quoting'])}\n"
        f"GUARDED: str = {wrapped_literal(definition['guarded'])}\n"
        f"EXEMPT_HEADS: tuple[str, ...] = (\n{exempt_heads})\n"
        f"FOLDS: dict[str, str] = {{{folds}}}\n"
        f"KINDS: tuple[str, ...] = (\n{kinds})\n"
        f"REASON: str = {wrapped_literal(definition['reason'])}\n"
        f"MAX_EVENT_INPUT: int = {definition['max_event_input']}\n"
        f"PASS_EXIT: int = {definition['pass_exit']}\n"
        "GUARDED_WORD: re.Pattern[str] = re.compile(GUARDED, re.IGNORECASE | re.ASCII)\n"
        "QUOTING_CHARS: re.Pattern[str] = re.compile(QUOTING)\n"
        "FOLD_TABLE: dict[int, str] = str.maketrans(FOLDS)\n"
        'ASSIGNMENT: re.Pattern[str] = re.compile("^[A-Za-z_][A-Za-z0-9_]*=")\n'
        'OPAQUE_SHELL: tuple[str, ...] = ("$(", "`", "<(", ">(")\n'
        'SEGMENT_BREAKS: frozenset[str] = frozenset(";\\n|()")\n'
        "QUOTED_ESCAPES: frozenset[str] = frozenset('$`\"\\\\\\n')\n\n\n"
        "def names_guarded(text: str) -> bool:\n"
        '    return GUARDED_WORD.search(QUOTING_CHARS.sub("", text).translate(FOLD_TABLE)) is not None\n\n\n'
        "# isinstance, not match: the plugin's bin/hook runs this under the first python3 on PATH, stock macOS 3.9 "
        "included.\n"
        "def names_guarded_value(value: object) -> bool:\n"
        "    if isinstance(value, str):\n"
        "        return names_guarded(value)\n"
        "    if isinstance(value, list):\n"
        "        items = cast(list[object], value)\n"
        "        words = [item for item in items if isinstance(item, str)]\n"
        '        return (len(words) == len(items) and names_guarded(" ".join(words))) or any(\n'
        "            names_guarded_value(item) for item in items\n"
        "        )\n"
        "    if isinstance(value, dict):\n"
        "        return any(names_guarded_value(item) for item in cast(dict[object, object], value).values())\n"
        "    return False\n\n\n"
        "def first_party_command(tool_input: object) -> bool:\n"
        "    if not isinstance(tool_input, dict):\n"
        "        return False\n"
        '    command = cast(dict[object, object], tool_input).get("command")\n'
        "    if not isinstance(command, str) or any(opaque in command for opaque in OPAQUE_SHELL):\n"
        "        return False\n"
        "    segments = shell_segments(command)\n"
        "    return segments is not None and all(exempt_segment(words) for words in segments)\n\n\n"
        "def exempt_segment(words: list[tuple[str, str, bool]]) -> bool:\n"
        "    for raw, cooked, redirect in words:\n"
        "        if ASSIGNMENT.match(raw) is None:\n"
        '            return not redirect and cooked.rpartition("/")[2] in EXEMPT_HEADS\n'
        "    return True\n\n\n"
        "def shell_segments(command: str) -> list[list[tuple[str, str, bool]]] | None:\n"
        "    segments: list[list[tuple[str, str, bool]]] = [[]]\n"
        "    raw: list[str] = []\n"
        "    cooked: list[str] = []\n"
        "    started = redirect = after_redirect = False\n\n"
        "    def end_word() -> None:\n"
        "        nonlocal started, redirect\n"
        "        if started:\n"
        '            segments[-1].append(("".join(raw), "".join(cooked), redirect))\n'
        "        raw.clear()\n"
        "        cooked.clear()\n"
        "        started = redirect = False\n\n"
        "    index = 0\n"
        "    while index < len(command):\n"
        "        char = command[index]\n"
        "        redirecting = False\n"
        '        if char == "\\\\" and index + 1 == len(command):\n'
        "            raw.append(char)\n"
        "            cooked.append(char)\n"
        "            started = True\n"
        '        elif char == "\\\\":\n'
        "            index += 1\n"
        '            if command[index] != "\\n":\n'
        "                raw.append(command[index - 1 : index + 1])\n"
        "                cooked.append(command[index])\n"
        "                started = True\n"
        '        elif char == "\'":\n'
        '            end = command.find("\'", index + 1)\n'
        "            if end < 0:\n"
        "                return None\n"
        "            raw.append(command[index : end + 1])\n"
        "            cooked.append(command[index + 1 : end])\n"
        "            started = True\n"
        "            index = end\n"
        "        elif char == '\"':\n"
        "            end = index + 1\n"
        "            while end < len(command) and command[end] != '\"':\n"
        '                escaped = command[end] == "\\\\" and end + 1 < len(command) and '
        "command[end + 1] in QUOTED_ESCAPES\n"
        "                end += escaped\n"
        '                if not (escaped and command[end] == "\\n"):\n'
        "                    cooked.append(command[end])\n"
        "                end += 1\n"
        "            if end == len(command):\n"
        "                return None\n"
        "            raw.append(command[index : end + 1])\n"
        "            started = True\n"
        "            index = end\n"
        '        elif char in " \\t":\n'
        "            end_word()\n"
        '        elif char in SEGMENT_BREAKS or (char == "&" and not after_redirect and '
        'command[index + 1 : index + 2] != ">"):\n'
        "            end_word()\n"
        "            segments.append([])\n"
        "        else:\n"
        "            raw.append(char)\n"
        "            cooked.append(char)\n"
        "            started = True\n"
        '            redirecting = char in "<>"\n'
        "            redirect = redirect or redirecting\n"
        "        after_redirect = redirecting\n"
        "        index += 1\n"
        "    end_word()\n"
        "    return segments\n\n\n"
        "def mandatory(event: str, payload: bytes) -> bool:\n"
        "    if event not in EVENTS:\n"
        "        return False\n"
        "    try:\n"
        '        fields = json.loads(payload.decode(errors="replace"))\n'
        "    except ValueError:\n"
        "        return False\n"
        "    if not isinstance(fields, dict):\n"
        "        return False\n"
        "    payload_fields = cast(dict[object, object], fields)\n"
        '    if payload_fields.get("tool_name") == "Bash" and first_party_command(payload_fields.get("tool_input")):\n'
        "        return False\n"
        '    return names_guarded_value(payload_fields.get("tool_name")) or '
        'names_guarded_value(payload_fields.get("tool_input"))\n\n\n'
        "def deny_envelope(event: str, kind: str) -> str:\n"
        "    if kind not in KINDS:\n"
        '        raise ValueError(f"unknown guard kind {kind!r}")\n'
        '    reason = REASON.replace("{kind}", kind)\n'
        "    output = (\n"
        '        {"hookEventName": event, "decision": {"behavior": "deny", "message": reason}}\n'
        '        if event == "PermissionRequest"\n'
        '        else {"hookEventName": event, "permissionDecision": "deny", "permissionDecisionReason": reason}\n'
        "    )\n"
        '    return json.dumps({"hookSpecificOutput": output}, sort_keys=True, separators=(",", ":"), '
        "ensure_ascii=False)\n\n\n"
        'def deny_if_mandatory(event: str, stdin: BinaryIO, *, prefix: bytes = b"") -> int:\n'
        "    if event not in EVENTS or not mandatory(event, prefix + stdin.read(MAX_EVENT_INPUT + 1)):\n"
        "        return PASS_EXIT\n"
        '    print(deny_envelope(event, "host-unavailable"))\n'
        "    return 0\n\n\n"
        "# bin/hook has read one byte of stdin to tell a refused resolver from a host that spent the payload; "
        "argv[2] carries it.\n"
        'if __name__ == "__main__":\n'
        "    raise SystemExit(deny_if_mandatory(sys.argv[1], sys.stdin.buffer, prefix=os.fsencode(sys.argv[2])))\n"
    )


def rendered_guard(definition: dict[str, Any]) -> ModuleType:
    module = ModuleType("guard_literal")
    exec(render_guard_literal(definition), module.__dict__)
    return module


def render_guard_shell(definition: dict[str, Any]) -> str:
    guard = rendered_guard(definition)
    denies = "".join(
        f"GUARD_DENY_{event}={shlex.quote(guard.deny_envelope(event, STATIC_DENY_KIND))}\n"
        for event in definition["events"]
    )
    return f"{GUARD_HEADER}GUARD_PASS_EXIT={definition['pass_exit']}\n{denies}"


def write_guard_literals(root: Path) -> None:
    definition = json.loads((root / GUARD_DEFINITION).read_text())
    rendered = render_guard_literal(definition)
    for relative in GUARD_LITERALS:
        (root / relative).write_text(rendered)
    (root / GUARD_SHELL).write_text(render_guard_shell(definition))


class CustomBuildHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version: str, build_data: dict[str, object]) -> None:
        write_langs(Path(self.root) / "captain_hook" / "langs.py")
        write_guard_literals(Path(self.root))


if __name__ == "__main__":
    write_langs(Path(__file__).parent / "captain_hook" / "langs.py")
    write_guard_literals(Path(__file__).parent)
