from __future__ import annotations

import ast
import os
import re
from collections import defaultdict
from collections.abc import Iterator
from contextlib import contextmanager
from functools import cache
from importlib.metadata import version
from pathlib import Path

from ast_grep_py import SgRoot
from hatchling.builders.hooks.plugin.interface import BuildHookInterface
from pygments.lexers import get_all_lexers

GLOB_PATTERN = re.compile(r"^\*\.([A-Za-z0-9_+-]+)$")
COMMENT_KIND_SEEDS = (
    "comment",
    "line_comment",
    "block_comment",
    "multiline_comment",
    "html_comment",
    "js_comment",
)
COMMENTLESS_LANGS = frozenset({"md"})
REGEN_COMMAND = "uv run python hatch_build.py"


@contextmanager
def suppress_stderr() -> Iterator[None]:
    saved = os.dup(2)
    try:
        with open(os.devnull, "w") as devnull:
            os.dup2(devnull.fileno(), 2)
            yield
    finally:
        os.dup2(saved, 2)
        os.close(saved)


@cache
def accepts_language(alias: str) -> bool:
    with suppress_stderr():
        try:
            SgRoot("", alias)
        # ast-grep raises a pyo3 PanicException outside Exception for unknown languages.
        except (KeyboardInterrupt, SystemExit):
            raise
        except BaseException:
            return False
    return True


@cache
def defines_comment_kind(lang: str, kind: str) -> bool:
    with suppress_stderr():
        try:
            SgRoot("", lang).root().find(kind=kind)
        except RuntimeError:
            return False
    return True


def build_lang_globs() -> dict[str, tuple[str, ...]]:
    claims: dict[str, set[tuple[str, str]]] = defaultdict(set)
    for _name, aliases, globs, _mimetypes in get_all_lexers():
        if not (accepted := tuple(alias for alias in aliases if accepts_language(alias))):
            continue
        lang = min(enumerate(accepted), key=lambda item: (len(item[1]), item[0]))[1]
        for glob in globs:
            if match := GLOB_PATTERN.fullmatch(glob):
                claims[match[1].lower()].add((match[1], lang))

    owners: dict[str, str] = {}
    for ext, ext_claims in sorted(claims.items()):
        claimants = {lang for _spelling, lang in ext_claims}
        if len(claimants) == 1:
            owners[ext] = claimants.pop()
            continue
        lowercase_claimants = {lang for spelling, lang in ext_claims if spelling == ext}
        if len(lowercase_claimants) != 1:
            raise ValueError(f"case-fold collision for extension {ext!r}: {sorted(claimants)!r}")
        owners[ext] = lowercase_claimants.pop()

    return {
        lang: tuple(f"*.{ext}" for ext, owner in sorted(owners.items()) if owner == lang)
        for lang in sorted(set(owners.values()))
    }


def build_comment_types() -> frozenset[str]:
    by_lang = {
        lang: frozenset(kind for kind in COMMENT_KIND_SEEDS if defines_comment_kind(lang, kind))
        for lang in build_lang_globs()
    }
    if missing := sorted(lang for lang, kinds in by_lang.items() if not kinds and lang not in COMMENTLESS_LANGS):
        raise RuntimeError(f"generated languages define none of {COMMENT_KIND_SEEDS!r}: {missing!r}")
    return frozenset(kind for kinds in by_lang.values() for kind in kinds)


def render_langs() -> str:
    lang_globs = build_lang_globs()
    comment_types = build_comment_types()
    globs_body = "\n".join(f"    {lang!r}: {globs!r}," for lang, globs in lang_globs.items())
    comments_body = "\n".join(f"        {kind!r}," for kind in sorted(comment_types))
    return (
        f"# GENERATED by `{REGEN_COMMAND}`.\n"
        f"# Pygments {version('pygments')}; ast-grep-py {version('ast-grep-py')}.\n\n"
        "from __future__ import annotations\n\n"
        "LANG_GLOBS: dict[str, tuple[str, ...]] = {\n"
        f"{globs_body}\n"
        "}\n\n"
        "COMMENT_TYPES: frozenset[str] = frozenset(\n"
        "    {\n"
        f"{comments_body}\n"
        "    }\n"
        ")\n"
    )


def write_langs(path: Path) -> None:
    path.write_text(render_langs())


def build_exports(path: Path) -> dict[str, str]:
    exports: dict[str, str] = {}
    for node in ast.parse(path.read_text()).body:
        if not isinstance(node, ast.ImportFrom) or node.module is None or node.level:
            raise ValueError(f"unexpected export stub statement: {ast.dump(node)}")
        for alias in node.names:
            if alias.asname != alias.name:
                raise ValueError(f"export must use `X as X`: {ast.unparse(node)}")
            if alias.name in exports:
                raise ValueError(f"duplicate export: {alias.name}")
            exports[alias.name] = f"captain_hook.{alias.name}" if node.module == "captain_hook" else node.module
    return exports


def render_exports(exports: dict[str, str]) -> str:
    body = "\n".join(f"    {name!r}: {module!r}," for name, module in exports.items())
    return (
        f"# GENERATED by `{REGEN_COMMAND}`.\n\n"
        "from __future__ import annotations\n\n"
        "EXPORTS: dict[str, str] = {\n"
        f"{body}\n"
        "}\n"
    )


def write_exports(stub: Path, path: Path) -> None:
    path.write_text(render_exports(build_exports(stub)))


class CustomBuildHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version: str, build_data: dict[str, object]) -> None:
        package = Path(self.root) / "captain_hook"
        write_langs(package / "langs.py")
        write_exports(package / "__init__.pyi", package / "exports.py")


if __name__ == "__main__":
    package = Path(__file__).parent / "captain_hook"
    write_langs(package / "langs.py")
    write_exports(package / "__init__.pyi", package / "exports.py")
