from __future__ import annotations

import importlib
import json
import re
import sys
from pathlib import Path
from string import ascii_lowercase
from typing import Any

import pytest

from capt_hook_client import guard_literal as shim
from captain_hook import guard_literal as guard
from captain_hook.app import _state
from captain_hook.builtin_packs.general.hooks import sessions
from captain_hook.testing.helpers import input_to_event
from captain_hook.types import Event
from captain_hook.worker.protocol import MAX_EVENT_INPUT
from tests.helpers import make_ctx

ROOT = Path(__file__).parents[1]
DEFINITION = json.loads((ROOT / "internal" / "wireproto" / "guard.json").read_text())
FIXTURE_TEXT = (ROOT / "internal" / "wireproto" / "guard_fixtures.json").read_text()
LOOKAROUND_OR_BACKREFERENCE = re.compile(r"\(\?<?[=!]|\\[1-9]|\(\?P=")
PARENT_GUARDED_WORD = re.compile(guard.GUARDED, re.IGNORECASE)
ASCII_LETTER = re.compile("[a-z]", re.IGNORECASE)
SPOOFED = ["\u212aill -9 -1", "\u212aillall claude", "\u017fhutdown -h now", "fu\u017fer -k 3000/tcp"]


def raw_payloads(text: str) -> list[bytes]:
    decoder = json.JSONDecoder()
    payloads: list[bytes] = []
    for key in re.finditer(r'"payload":\s*', text):
        _, end = decoder.raw_decode(text, key.end())
        payloads.append(text[key.end() : end].encode())
    return payloads


FIXTURES: list[dict[str, Any]] = [
    fixture | {"payload_raw": raw}
    for fixture, raw in zip(json.loads(FIXTURE_TEXT), raw_payloads(FIXTURE_TEXT), strict=True)
]


def payload_bytes(fixture: dict[str, Any]) -> bytes:
    return fixture["payload_raw"]


def parent_names_guarded(text: str) -> bool:
    return PARENT_GUARDED_WORD.search(guard.QUOTING_CHARS.sub("", text)) is not None


def guarded_names() -> list[str]:
    match = re.fullmatch(r"\\b\((.*)\)\\b", guard.GUARDED)
    assert match is not None
    return match.group(1).split("|")


def test_both_renderings_are_byte_identical_and_generated() -> None:
    assert Path(shim.__file__).read_bytes() == Path(guard.__file__).read_bytes()
    assert Path(shim.__file__).read_text().startswith("# GENERATED by `uv run python hatch_build.py`")


def test_rendered_constants_are_the_definition() -> None:
    assert guard.EVENTS == frozenset(DEFINITION["events"])
    assert guard.QUOTING == DEFINITION["quoting"]
    assert guard.GUARDED == DEFINITION["guarded"]
    assert guard.FOLDS == DEFINITION["folds"]
    assert guard.KINDS == tuple(DEFINITION["kinds"])
    assert guard.REASON == DEFINITION["reason"]
    assert guard.MAX_EVENT_INPUT == DEFINITION["max_event_input"] == MAX_EVENT_INPUT


def test_fixture_payloads_are_read_as_the_bytes_go_reads() -> None:
    for fixture in FIXTURES:
        assert json.loads(fixture["payload_raw"]) == fixture["payload"], fixture["name"]
    escaped = next(fixture for fixture in FIXTURES if fixture["name"] == "json unicode escape in the name")
    assert b"\\u006bill" in escaped["payload_raw"]
    assert b"kill" not in escaped["payload_raw"]


@pytest.mark.parametrize("fixture", FIXTURES, ids=[fixture["name"] for fixture in FIXTURES])
def test_fixtures_agree_across_renderings(fixture: dict[str, Any]) -> None:
    payload = payload_bytes(fixture)
    assert shim.mandatory(fixture["event"], payload) is guard.mandatory(fixture["event"], payload)
    assert guard.mandatory(fixture["event"], payload) is fixture["mandatory"]


def test_guarded_alternation_is_exactly_the_guards_prefilter_set() -> None:
    assert set(guarded_names()) == {*sessions.GUARDED_PROGRAMS, *sessions.LAUNCHERS, "find"}
    assert sessions.names_guarded is guard.names_guarded
    assert sessions.QUOTING_CHARS is guard.QUOTING_CHARS


def test_regex_dialect_is_valid_in_both_engines() -> None:
    for pattern in (guard.GUARDED, guard.QUOTING):
        re.compile(pattern)
        assert LOOKAROUND_OR_BACKREFERENCE.search(pattern) is None


def test_folds_cover_every_code_point_unicode_case_folding_reads_as_a_letter() -> None:
    folded = {
        char: next(letter for letter in ascii_lowercase if re.fullmatch(letter, char, re.IGNORECASE))
        for code in range(0x80, sys.maxunicode + 1)
        if ASCII_LETTER.fullmatch(char := chr(code))
    }
    assert folded.items() <= guard.FOLDS.items()
    assert all(ord(source) > 0x7F and target in ascii_lowercase for source, target in guard.FOLDS.items())


@pytest.mark.parametrize("text", SPOOFED)
def test_spoofed_spellings_stay_inside_the_parent_guards_scope(text: str) -> None:
    assert parent_names_guarded(text)
    assert guard.names_guarded(text)
    assert guard.mandatory("PreToolUse", json.dumps({"tool_name": "Bash", "tool_input": {"command": text}}).encode())
    evt = input_to_event(Event.PreToolUse, sessions.guarded(command=text))
    assert sessions.names_a_guarded_program(evt)


def test_every_folded_spelling_of_every_guarded_name_matches_as_the_parent_did() -> None:
    spellings = [
        f"{name[:index]}{source}{name[index + 1 :]} -9 1"
        for name in guarded_names()
        for index, letter in enumerate(name)
        for source, target in guard.FOLDS.items()
        if target == letter
    ]
    assert len(spellings) > 40
    for text in spellings:
        assert parent_names_guarded(text), text
        assert guard.names_guarded(text), text


def guard_rows() -> list[Any]:
    _state.hooks.clear()
    importlib.reload(sessions)
    entry = next(hook for hook in _state.hooks if hook.name == "guard_sessions")
    assert entry.spec.mandatory is True
    assert entry.spec.tests is not None
    return [key for key in entry.spec.tests if not isinstance(key, str)]


def test_every_inline_guard_row_the_prefilter_matches_is_mandatory() -> None:
    rows = guard_rows()
    matched = 0
    for row in rows:
        evt = input_to_event(Event.PreToolUse, row)
        raw = json.dumps(evt._raw).encode()
        if sessions.names_a_guarded_program(evt):
            matched += 1
            assert guard.mandatory("PreToolUse", raw), row
            assert guard.mandatory("PermissionRequest", raw), row
    assert matched > 40


@pytest.mark.parametrize("fixture", FIXTURES, ids=[fixture["name"] for fixture in FIXTURES])
def test_every_fixture_the_prefilter_matches_is_mandatory(fixture: dict[str, Any]) -> None:
    if fixture["event"] not in guard.EVENTS:
        return
    evt = Event[fixture["event"]].event_class(_raw=fixture["payload"], ctx=make_ctx())
    if sessions.names_a_guarded_program(evt):
        assert fixture["mandatory"] is True


@pytest.mark.parametrize(
    ("payload", "mandatory"),
    [
        (b'{"tool_name":"Bash","tool_input":{"command":"\\u006bill 14575"}}', True),
        (b'{"tool_name":"Bash","tool_input":{"command":"p\\\\kill node"}}', True),
        (b'{"tool_name":"Bash","tool_input":{"command":"[k]ill 1"}}', True),
        (b'{"tool_name":"Bash","tool_input":{"command":"pkill \xff"}}', True),
        (b'{"tool_name":"mcp__x__y","tool_input":{"steps":[{"run":["renice","-n","5"]}]}}', True),
        (b'{"tool_name":"orca","tool_input":{"verb":"list"}}', True),
        (b'{"tool_name":"mcp__x__y","tool_input":{"argv":["pk","ill"]}}', False),
        (b'{"tool_name":"Bash","tool_input":{"kill":"nothing here"}}', False),
        (b'{"tool_name":"Bash","tool_input":{"command":"echo ok"},"transcript_path":"/t/killall.jsonl"}', False),
        (b'{"tool_name":"Bash","tool_input":{"command":"pkill', False),
        (b'["pkill"]', False),
        (b"", False),
    ],
    ids=[
        "unicode escape",
        "backslash in the name",
        "bracketed name",
        "invalid utf-8 beside the name",
        "deep list of dicts",
        "tool name alone",
        "split across items",
        "name only in a key",
        "name outside tool_input",
        "malformed",
        "not an object",
        "empty",
    ],
)
def test_mandatory_decodes_the_payload_rather_than_scanning_it(payload: bytes, mandatory: bool) -> None:
    assert guard.mandatory("PreToolUse", payload) is mandatory


def test_deny_envelopes_match_the_go_renderings_byte_for_byte() -> None:
    reason = (
        "BLOCKED: the session guard did not complete (host-unavailable) and this call names a session-ending "
        "program, so it stays denied (AGENTS.md § Protect Existing Sessions). Retry once the Captain Hook host "
        "answers, or ask the owner to run it."
    )
    assert guard.deny_envelope("PreToolUse", "host-unavailable") == (
        '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny",'
        f'"permissionDecisionReason":"{reason}"}}}}'
    )
    assert guard.deny_envelope("PermissionRequest", "host-unavailable") == (
        f'{{"hookSpecificOutput":{{"decision":{{"behavior":"deny","message":"{reason}"}},'
        '"hookEventName":"PermissionRequest"}}'
    )
    for kind in guard.KINDS:
        envelope = json.loads(guard.deny_envelope("PreToolUse", kind))
        assert f"({kind})" in envelope["hookSpecificOutput"]["permissionDecisionReason"]
    with pytest.raises(ValueError, match="guessed"):
        guard.deny_envelope("PreToolUse", "guessed")
