from __future__ import annotations

import ast
import importlib
import io
import json
import re
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from string import ascii_lowercase
from typing import Any

import pytest

from capt_hook_client import guard_literal as shim
from captain_hook import Allow, Block
from captain_hook import guard_literal as guard
from captain_hook.app import _state
from captain_hook.builtin_packs.general.hooks import _sessions as session_guard
from captain_hook.builtin_packs.general.hooks import sessions, stops
from captain_hook.testing.helpers import input_to_event
from captain_hook.types import Event
from captain_hook.worker.protocol import MAX_EVENT_INPUT
from hatch_build import STATIC_DENY_KIND, render_guard_literal, render_guard_shell
from tests.helpers import BENIGN_PAYLOAD, DESTRUCTIVE_PAYLOAD, STOP_PAYLOAD, make_ctx

ROOT = Path(__file__).parents[1]
DEFINITION = json.loads((ROOT / "internal" / "wireproto" / "guard.json").read_text())
SHELL_LITERAL = ROOT / "captain_hook" / "guard_literal.sh"
FIXTURE_TEXT = (ROOT / "internal" / "wireproto" / "guard_fixtures.json").read_text()
LOOKAROUND_OR_BACKREFERENCE = re.compile(r"\(\?<?[=!]|\\[1-9]|\(\?P=")
PARENT_GUARDED_WORD = re.compile(guard.GUARDED, re.IGNORECASE)
ASCII_LETTER = re.compile("[a-z]", re.IGNORECASE)
SPOOFED = ["\u212aill -9 -1", "\u212aillall claude", "\u017fhutdown -h now", "fu\u017fer -k 3000/tcp"]
ENVELOPES = {event: guard.deny_envelope(event, "host-unavailable") + "\n" for event in sorted(guard.EVENTS)}
STOCK_MACOS_PYTHON = Path("/usr/bin/python3")
STOCK_MACOS_GRAMMAR = (3, 9)
INTERPRETERS = [
    pytest.param(sys.executable, id="venv"),
    pytest.param(
        str(STOCK_MACOS_PYTHON),
        id="stock-macos",
        marks=pytest.mark.skipif(
            sys.platform != "darwin" or not STOCK_MACOS_PYTHON.is_file(), reason="the stock macOS python3"
        ),
    ),
]


def raw_payloads(text: str) -> list[bytes]:
    decoder = json.JSONDecoder()
    payloads: list[bytes] = []
    for key in re.finditer(r'"payload":\s*', text):
        _, end = decoder.raw_decode(text, key.end())
        payloads.append(text[key.end() : end].encode())
    return payloads


FIXTURES: list[dict[str, Any]] = [
    fixture | {"payload_raw": raw}
    for fixture, raw in zip(json.loads(FIXTURE_TEXT), raw_payloads(FIXTURE_TEXT), strict=True)
]


def payload_bytes(fixture: dict[str, Any]) -> bytes:
    return fixture["payload_raw"]


def parent_names_guarded(text: str) -> bool:
    return PARENT_GUARDED_WORD.search(guard.QUOTING_CHARS.sub("", text)) is not None


def guarded_names() -> list[str]:
    match = re.fullmatch(r"\\b\((.*)\)\\b", guard.GUARDED)
    assert match is not None
    return match.group(1).split("|")


def test_both_renderings_are_byte_identical_and_generated() -> None:
    assert Path(shim.__file__).read_bytes() == Path(guard.__file__).read_bytes()
    assert Path(shim.__file__).read_text().startswith("# GENERATED by `uv run python hatch_build.py`")


@pytest.mark.parametrize(
    ("relative", "render"),
    [
        pytest.param("captain_hook/guard_literal.py", render_guard_literal, id="python"),
        pytest.param("captain_hook/guard_literal.sh", render_guard_shell, id="shell"),
    ],
)
def test_tracked_rendering_is_the_definition_rendered(relative: str, render: Callable[[dict[str, Any]], str]) -> None:
    rendered = render(DEFINITION)
    assert (ROOT / relative).read_text() == rendered
    staged = subprocess.run(["git", "show", f":{relative}"], cwd=ROOT, capture_output=True, text=True, check=True)
    assert staged.stdout == rendered


def shell_value(name: str) -> str:
    return subprocess.run(
        ["/bin/bash", "-c", f'. "$1"; printf %s "${name}"', "guard", str(SHELL_LITERAL)],
        capture_output=True,
        text=True,
        check=True,
    ).stdout


def test_shell_rendering_carries_the_pass_exit_and_the_static_envelopes() -> None:
    lines = SHELL_LITERAL.read_text().splitlines()
    assert lines[0].startswith("# GENERATED by `uv run python hatch_build.py`")
    assert [line.partition("=")[0] for line in lines[1:]] == [
        "GUARD_PASS_EXIT",
        *(f"GUARD_DENY_{event}" for event in DEFINITION["events"]),
    ]
    assert shell_value("GUARD_PASS_EXIT") == str(guard.PASS_EXIT)
    for event in DEFINITION["events"]:
        assert shell_value(f"GUARD_DENY_{event}") == guard.deny_envelope(event, STATIC_DENY_KIND)


@pytest.mark.parametrize(
    ("event", "payload", "code", "output"),
    [
        pytest.param("PreToolUse", DESTRUCTIVE_PAYLOAD, 0, ENVELOPES["PreToolUse"], id="destructive PreToolUse"),
        pytest.param(
            "PermissionRequest",
            DESTRUCTIVE_PAYLOAD,
            0,
            ENVELOPES["PermissionRequest"],
            id="destructive PermissionRequest",
        ),
        pytest.param("PreToolUse", STOP_PAYLOAD, 0, ENVELOPES["PreToolUse"], id="stop tool PreToolUse"),
        pytest.param(
            "PermissionRequest", STOP_PAYLOAD, 0, ENVELOPES["PermissionRequest"], id="stop tool PermissionRequest"
        ),
        pytest.param("PreToolUse", BENIGN_PAYLOAD, guard.PASS_EXIT, "", id="benign"),
    ],
)
def test_deny_if_mandatory_prints_the_envelope_only_for_a_mandatory_call(
    event: str, payload: bytes, code: int, output: str, capsys: pytest.CaptureFixture[str]
) -> None:
    assert guard.deny_if_mandatory(event, io.BytesIO(payload)) == code
    assert capsys.readouterr().out == output


def test_deny_if_mandatory_never_reads_stdin_for_an_unguarded_event(capsys: pytest.CaptureFixture[str]) -> None:
    stdin = io.BytesIO(DESTRUCTIVE_PAYLOAD)
    assert guard.deny_if_mandatory("Stop", stdin) == guard.PASS_EXIT
    assert stdin.tell() == 0
    assert capsys.readouterr().out == ""


def test_rendering_parses_under_the_stock_macos_python_grammar() -> None:
    """PIN: bin/hook runs the literal under the first python3 on PATH, which on a stock Mac is 3.9."""
    ast.parse(Path(guard.__file__).read_text(), feature_version=STOCK_MACOS_GRAMMAR)


@pytest.mark.parametrize("interpreter", INTERPRETERS)
@pytest.mark.parametrize(
    ("event", "payload", "code", "output"),
    [
        pytest.param("PreToolUse", DESTRUCTIVE_PAYLOAD, 0, ENVELOPES["PreToolUse"], id="destructive"),
        pytest.param("PermissionRequest", DESTRUCTIVE_PAYLOAD, 0, ENVELOPES["PermissionRequest"], id="destructive-pr"),
        pytest.param("PreToolUse", STOP_PAYLOAD, 0, ENVELOPES["PreToolUse"], id="stop"),
        pytest.param("PermissionRequest", STOP_PAYLOAD, 0, ENVELOPES["PermissionRequest"], id="stop-pr"),
        pytest.param("PreToolUse", BENIGN_PAYLOAD, guard.PASS_EXIT, "", id="benign"),
        pytest.param("Stop", DESTRUCTIVE_PAYLOAD, guard.PASS_EXIT, "", id="unguarded"),
    ],
)
def test_module_entry_exits_with_the_verdict(
    interpreter: str, event: str, payload: bytes, code: int, output: str
) -> None:
    """PIN: the entry takes the one byte bin/hook read off stdin as argv[2] and reads the rest from stdin."""
    result = subprocess.run(
        [interpreter, "-I", guard.__file__, event, payload[:1].decode()],
        input=payload[1:],
        capture_output=True,
        check=False,
    )
    assert (result.returncode, result.stdout.decode(), result.stderr) == (code, output, b"")


def test_rendered_constants_are_the_definition() -> None:
    assert guard.EVENTS == frozenset(DEFINITION["events"])
    assert guard.TOOLS == frozenset(DEFINITION["tools"])
    assert guard.QUOTING == DEFINITION["quoting"]
    assert guard.GUARDED == DEFINITION["guarded"]
    assert guard.EXEMPT_HEADS == tuple(DEFINITION["exempt_heads"])
    assert guard.FOLDS == DEFINITION["folds"]
    assert guard.KINDS == tuple(DEFINITION["kinds"])
    assert guard.REASON == DEFINITION["reason"]
    assert guard.MAX_EVENT_INPUT == DEFINITION["max_event_input"] == MAX_EVENT_INPUT
    assert guard.PASS_EXIT == DEFINITION["pass_exit"]
    assert STATIC_DENY_KIND in guard.KINDS


def test_fixture_payloads_are_read_as_the_bytes_go_reads() -> None:
    for fixture in FIXTURES:
        assert json.loads(fixture["payload_raw"]) == fixture["payload"], fixture["name"]
    escaped = next(fixture for fixture in FIXTURES if fixture["name"] == "json unicode escape in the name")
    assert b"\\u006bill" in escaped["payload_raw"]
    assert b"kill" not in escaped["payload_raw"]


@pytest.mark.parametrize("fixture", FIXTURES, ids=[fixture["name"] for fixture in FIXTURES])
def test_fixtures_agree_across_renderings(fixture: dict[str, Any]) -> None:
    payload = payload_bytes(fixture)
    assert shim.mandatory(fixture["event"], payload) is guard.mandatory(fixture["event"], payload)
    assert guard.mandatory(fixture["event"], payload) is fixture["mandatory"]


def test_guarded_alternation_is_exactly_the_guards_prefilter_set() -> None:
    assert set(guarded_names()) == {*session_guard.GUARDED_PROGRAMS, *session_guard.LAUNCHERS, "find"}
    assert session_guard.names_guarded is guard.names_guarded
    assert session_guard.QUOTING_CHARS is guard.QUOTING_CHARS


def test_regex_dialect_is_valid_in_both_engines() -> None:
    for pattern in (guard.GUARDED, guard.QUOTING):
        re.compile(pattern)
        assert LOOKAROUND_OR_BACKREFERENCE.search(pattern) is None


def test_folds_cover_every_code_point_unicode_case_folding_reads_as_a_letter() -> None:
    folded = {
        char: next(letter for letter in ascii_lowercase if re.fullmatch(letter, char, re.IGNORECASE))
        for code in range(0x80, sys.maxunicode + 1)
        if ASCII_LETTER.fullmatch(char := chr(code))
    }
    assert folded.items() <= guard.FOLDS.items()
    assert all(ord(source) > 0x7F and target in ascii_lowercase for source, target in guard.FOLDS.items())


@pytest.mark.parametrize("text", SPOOFED)
def test_spoofed_spellings_stay_inside_the_parent_guards_scope(text: str) -> None:
    assert parent_names_guarded(text)
    assert guard.names_guarded(text)
    assert guard.mandatory("PreToolUse", json.dumps({"tool_name": "Bash", "tool_input": {"command": text}}).encode())
    evt = input_to_event(Event.PreToolUse, session_guard.guarded(command=text))
    assert session_guard.names_a_guarded_program(evt)


def test_every_folded_spelling_of_every_guarded_name_matches_as_the_parent_did() -> None:
    spellings = [
        f"{name[:index]}{source}{name[index + 1 :]} -9 1"
        for name in guarded_names()
        for index, letter in enumerate(name)
        for source, target in guard.FOLDS.items()
        if target == letter
    ]
    assert len(spellings) > 40
    for text in spellings:
        assert parent_names_guarded(text), text
        assert guard.names_guarded(text), text


def guard_rows() -> list[tuple[Any, object]]:
    _state.hooks.clear()
    importlib.reload(sessions)
    guards = [hook for hook in _state.hooks if hook.spec.mandatory]
    assert len(guards) == len(_state.hooks) > 1
    assert all(hook.spec.tests for hook in guards)
    return [
        (key, expected)
        for hook in guards
        for key, expected in (hook.spec.tests or {}).items()
        if not isinstance(key, str)
    ]


def test_stop_tools_are_the_stop_guards_names_and_flag_exactly_the_rows_it_blocks() -> None:
    _state.hooks.clear()
    importlib.reload(stops)
    assert set(DEFINITION["tools"]) == set(stops.STOP_TOOLS)
    [stop_guard] = _state.hooks
    assert stop_guard.spec.mandatory
    rows = [(row, expected) for row, expected in (stop_guard.spec.tests or {}).items() if not isinstance(row, str)]
    assert len(rows) > 8
    for row, expected in rows:
        for event in (Event.PreToolUse, Event.PermissionRequest):
            raw = json.dumps(input_to_event(event, row)._raw).encode()
            assert guard.mandatory(event.name, raw) is isinstance(expected, Block), (event, row)


def test_every_inline_guard_row_the_prefilter_matches_is_mandatory_or_allowed() -> None:
    rows = guard_rows()
    matched = 0
    for row, expected in rows:
        evt = input_to_event(Event.PreToolUse, row)
        raw = json.dumps(evt._raw).encode()
        if session_guard.names_a_guarded_program(evt):
            matched += 1
            assert guard.mandatory("PreToolUse", raw) or isinstance(expected, Allow), row
            assert guard.mandatory("PermissionRequest", raw) == guard.mandatory("PreToolUse", raw), row
    assert matched > 40


@pytest.mark.parametrize("fixture", FIXTURES, ids=[fixture["name"] for fixture in FIXTURES])
def test_every_fixture_the_prefilter_matches_is_mandatory_or_first_party(fixture: dict[str, Any]) -> None:
    if fixture["event"] not in guard.EVENTS:
        return
    evt = Event[fixture["event"]].event_class(_raw=fixture["payload"], ctx=make_ctx())
    if session_guard.names_a_guarded_program(evt):
        assert fixture["mandatory"] or guard.first_party_command(fixture["payload"]["tool_input"])


@pytest.mark.parametrize(
    ("payload", "mandatory"),
    [
        (b'{"tool_name":"Bash","tool_input":{"command":"\\u006bill 14575"}}', True),
        (b'{"tool_name":"Bash","tool_input":{"command":"p\\\\kill node"}}', True),
        (b'{"tool_name":"Bash","tool_input":{"command":"[k]ill 1"}}', True),
        (b'{"tool_name":"Bash","tool_input":{"command":"pkill \xff"}}', True),
        (b'{"tool_name":"mcp__x__y","tool_input":{"steps":[{"run":["renice","-n","5"]}]}}', True),
        (b'{"tool_name":"orca","tool_input":{"verb":"list"}}', True),
        (b'{"tool_name":"TaskStop","tool_input":{"task_id":"wcn64vfub"}}', True),
        (b'{"tool_name":"TaskStop","tool_input":{"shell_id":"bash_3"}}', True),
        (b'{"tool_name":"TaskStop"}', True),
        (b'{"tool_name":"TaskOutput","tool_input":{"task_id":"wcn64vfub"}}', False),
        (b'{"tool_name":"mcp__orca__TaskStop","tool_input":{"task_id":"wcn64vfub"}}', False),
        (b'{"tool_name":["TaskStop"],"tool_input":{"task_id":"wcn64vfub"}}', False),
        (b'{"tool_name":{"name":"TaskStop"},"tool_input":{}}', False),
        (b'{"tool_name":"mcp__x__y","tool_input":{"argv":["pk","ill"]}}', False),
        (b'{"tool_name":"Bash","tool_input":{"kill":"nothing here"}}', False),
        (b'{"tool_name":"Bash","tool_input":{"command":"echo ok"},"transcript_path":"/t/killall.jsonl"}', False),
        (b'{"tool_name":"Bash","tool_input":{"command":"pkill', False),
        (b'["pkill"]', False),
        (b"", False),
    ],
    ids=[
        "unicode escape",
        "backslash in the name",
        "bracketed name",
        "invalid utf-8 beside the name",
        "deep list of dicts",
        "tool name alone",
        "stop tool by task id",
        "stop tool by retired shell id",
        "stop tool with no input",
        "task output is not a stop",
        "mcp tool named like the stop tool",
        "stop tool name in a list",
        "stop tool name in a dict",
        "split across items",
        "name only in a key",
        "name outside tool_input",
        "malformed",
        "not an object",
        "empty",
    ],
)
def test_mandatory_decodes_the_payload_rather_than_scanning_it(payload: bytes, mandatory: bool) -> None:
    assert guard.mandatory("PreToolUse", payload) is mandatory


def test_deny_envelopes_match_the_go_renderings_byte_for_byte() -> None:
    reason = (
        "BLOCKED: the session guard did not complete (host-unavailable), so this call could not be checked for "
        "a session-ending program and stays denied (AGENTS.md § Protect Existing Sessions). Retry once the Captain "
        "Hook host answers, or ask the owner to install the host or run the call themselves."
    )
    assert guard.deny_envelope("PreToolUse", "host-unavailable") == (
        '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny",'
        f'"permissionDecisionReason":"{reason}"}}}}'
    )
    assert guard.deny_envelope("PermissionRequest", "host-unavailable") == (
        f'{{"hookSpecificOutput":{{"decision":{{"behavior":"deny","message":"{reason}"}},'
        '"hookEventName":"PermissionRequest"}}'
    )
    for kind in guard.KINDS:
        envelope = json.loads(guard.deny_envelope("PreToolUse", kind))
        assert f"({kind})" in envelope["hookSpecificOutput"]["permissionDecisionReason"]
    with pytest.raises(ValueError, match="guessed"):
        guard.deny_envelope("PreToolUse", "guessed")
