from __future__ import annotations

from captain_hook.app import HookApp, get_current_app, hook
from captain_hook.classifiers import MessageClassifier
from captain_hook.classifiers import detect as detect_classifier
from captain_hook.cli import generate_settings, generate_settings_json
from captain_hook.utils import read_json
from captain_hook.command import Command, CommandLine, Redirect
from captain_hook.conditions import check_condition, matches_conditions
from captain_hook.context import HookContext
from captain_hook.dispatch import dispatch, execute_hook, format_output, run_declarative
from captain_hook.events import (
    BaseHookEvent,
    NotificationEvent,
    PostToolUseEvent,
    PostToolUseFailureEvent,
    PreCompactEvent,
    PreToolUseEvent,
    StopEvent,
    SubagentStartEvent,
    SubagentStopEvent,
    ToolHookEvent,
    UserPromptSubmitEvent,
)
from captain_hook.file import File, PathMatcher
from captain_hook.primitives import (
    GateVerdict,
    NudgeVerdict,
    PromptCheckVerdict,
    block_command,
    gate,
    lint,
    llm_gate,
    llm_nudge,
    nudge,
    prompt_check,
    warn_command,
)
from captain_hook.primitives.llm import llm_evaluate
from captain_hook.prompt import Prompt, PromptMessage
from captain_hook.session import SessionSlot, SessionStore, cleanup_stale, ensure_session, session_hash, state_root
from captain_hook.settings import AutoConf, HooksSettings, build_settings
from captain_hook.signals import cite_message, extract_signal_context, resolve_signals, score_signals, transcript_texts
from captain_hook.signals.nlp import Clause, NlpSignal, Phrase, dep_related, nlp_scan
from captain_hook.state import (
    HookState,
    PrimitiveState,
    fired_this_turn,
    hook_name,
    record_fire,
    text_hash,
)
from captain_hook.testing import Allow, Block, Input, TranscriptFixture, Warn
from captain_hook.testing import TTest as TTest
from captain_hook.testing.helpers import (
    assert_result,
    dispatch_test,
    input_to_event,
    mock_event,
    mock_stop_event,
    mock_subagent_start_event,
    mock_subagent_stop_event,
    mock_tool_event,
    mock_user_prompt_event,
    run_inline_tests,
)
from captain_hook.tools import EditOp, TaskOp, WriteOp
from captain_hook.transcript import (
    ToolUse,
    ToolUseQuery,
    ToolUseSequence,
    Transcript,
    TranscriptMessage,
    TranscriptSlice,
    Turn,
)
from captain_hook.transcript.inputs import (
    AgentInput,
    BashInput,
    EditInput,
    FileInputBase,
    GenericInput,
    GlobInput,
    GrepInput,
    InputBase,
    ReadInput,
    SkillInput,
    TaskCreateInput,
    TaskUpdateInput,
    WriteInput,
    parse_tool_input,
)
from captain_hook.transcript.models import (
    ContentBlock,
    TextBlock,
    ToolResult,
    ToolUseBlock,
    parse_content_block,
)
from captain_hook.types import (
    Action,
    Agent,
    Content,
    CustomCondition,
    Event,
    FilePath,
    HookResult,
    HookSpec,
    InPlanMode,
    RanCommand,
    ReadFile,
)
from captain_hook.types import RegisteredHook as RegisteredHook
from captain_hook.types import Signal as Signal
from captain_hook.types import Signals as Signals
from captain_hook.types import TCondition as TCondition
from captain_hook.types import TestFile as TestFile
from captain_hook.types import Tool as Tool
from captain_hook.types import TouchedFile as TouchedFile
from captain_hook.types import UsedSkill as UsedSkill
from captain_hook.types import tokens_to_regex as tokens_to_regex
from captain_hook.workflow import Artifact, Step, Workflow, text_matches
from captain_hook.workflow import workflow as workflow

__all__ = [
    "CommandLine",
    "File",
    "HookApp",
    "PathMatcher",
    "Redirect",
    "Action",
    "Agent",
    "BaseHookEvent",
    "Command",
    "Content",
    "CustomCondition",
    "Event",
    "FilePath",
    "HookResult",
    "HookSpec",
    "InPlanMode",
    "NotificationEvent",
    "PostToolUseEvent",
    "PostToolUseFailureEvent",
    "PreCompactEvent",
    "PreToolUseEvent",
    "RanCommand",
    "ReadFile",
    "RegisteredHook",
    "Signal",
    "Signals",
    "StopEvent",
    "SubagentStartEvent",
    "SubagentStopEvent",
    "TCondition",
    "TestFile",
    "Tool",
    "ToolHookEvent",
    "TouchedFile",
    "UsedSkill",
    "UserPromptSubmitEvent",
    "HookContext",
    "SessionSlot",
    "SessionStore",
    "cleanup_stale",
    "ensure_session",
    "session_hash",
    "state_root",
    "HookState",
    "PrimitiveState",
    "fired_this_turn",
    "hook_name",
    "record_fire",
    "text_hash",
    "check_condition",
    "cite_message",
    "dispatch",
    "execute_hook",
    "extract_signal_context",
    "format_output",
    "block_command",
    "gate",
    "GateVerdict",
    "get_current_app",
    "lint",
    "llm_evaluate",
    "llm_gate",
    "llm_nudge",
    "matches_conditions",
    "nudge",
    "NudgeVerdict",
    "prompt_check",
    "PromptCheckVerdict",
    "resolve_signals",
    "run_declarative",
    "score_signals",
    "tokens_to_regex",
    "transcript_texts",
    "warn_command",
    "Prompt",
    "PromptMessage",
    "AutoConf",
    "HooksSettings",
    "build_settings",
    "generate_settings",
    "generate_settings_json",
    "EditOp",
    "TaskOp",
    "Transcript",
    "TranscriptMessage",
    "TranscriptSlice",
    "ToolUse",
    "ToolUseQuery",
    "ToolUseSequence",
    "Turn",
    "WriteOp",
    "AgentInput",
    "BashInput",
    "ContentBlock",
    "EditInput",
    "FileInputBase",
    "GenericInput",
    "GlobInput",
    "GrepInput",
    "InputBase",
    "ReadInput",
    "SkillInput",
    "TaskCreateInput",
    "TaskUpdateInput",
    "TextBlock",
    "ToolResult",
    "ToolUseBlock",
    "WriteInput",
    "parse_content_block",
    "parse_tool_input",
    "Clause",
    "NlpSignal",
    "Phrase",
    "dep_related",
    "nlp_scan",
    "Allow",
    "Block",
    "Input",
    "TranscriptFixture",
    "TTest",
    "Warn",
    "assert_result",
    "detect_classifier",
    "dispatch_test",
    "input_to_event",
    "MessageClassifier",
    "mock_event",
    "mock_stop_event",
    "mock_subagent_start_event",
    "mock_subagent_stop_event",
    "mock_tool_event",
    "mock_user_prompt_event",
    "run_inline_tests",
    "Artifact",
    "Step",
    "Workflow",
    "text_matches",
    "workflow",
    "hook",
    "read_json",
]
