from __future__ import annotations

from importlib import import_module

EXPORTS: dict[str, str] = {
    "Command": "cc_transcript.command",
    "CommandLine": "cc_transcript.command",
    "Occurrence": "cc_transcript.command",
    "Redirect": "cc_transcript.command",
    "Word": "cc_transcript.command",
    "BashCall": "cc_transcript.tools",
    "EditCall": "cc_transcript.tools",
    "ExitPlanModeCall": "cc_transcript.tools",
    "GlobCall": "cc_transcript.tools",
    "GrepCall": "cc_transcript.tools",
    "MultiEditCall": "cc_transcript.tools",
    "NotebookEditCall": "cc_transcript.tools",
    "OtherCall": "cc_transcript.tools",
    "ReadCall": "cc_transcript.tools",
    "SkillCall": "cc_transcript.tools",
    "TaskCall": "cc_transcript.tools",
    "TaskCreateCall": "cc_transcript.tools",
    "TaskUpdateCall": "cc_transcript.tools",
    "ToolCall": "cc_transcript.tools",
    "ToolCallBase": "cc_transcript.tools",
    "WriteCall": "cc_transcript.tools",
    "file": "captain_hook.file",
    "style": "captain_hook.style",
    "util": "captain_hook.util",
    "hook": "captain_hook.app",
    "on": "captain_hook.app",
    "COMMENT_TYPES": "captain_hook.ast_grep",
    "Edit": "captain_hook.ast_grep",
    "Match": "captain_hook.ast_grep",
    "SyntaxNode": "captain_hook.ast_grep",
    "Call": "captain_hook.cmd",
    "Cmd": "captain_hook.cmd",
    "Expansion": "captain_hook.cmd",
    "Target": "captain_hook.cmd",
    "Targets": "captain_hook.cmd",
    "Commits": "captain_hook.conditions",
    "EditedSource": "captain_hook.conditions",
    "FreshSession": "captain_hook.conditions",
    "FromTeammate": "captain_hook.conditions",
    "Headless": "captain_hook.conditions",
    "Redirects": "captain_hook.conditions",
    "RewritingExistingPlan": "captain_hook.conditions",
    "ScratchPath": "captain_hook.conditions",
    "UserSaid": "captain_hook.conditions",
    "workflow_opt_matches": "captain_hook.conditions",
    "workflow_opt_values": "captain_hook.conditions",
    "workflow_script_source": "captain_hook.conditions",
    "HookContext": "captain_hook.context",
    "AfterEdit": "captain_hook.contexts",
    "BeforeEdit": "captain_hook.contexts",
    "Excerpts": "captain_hook.contexts",
    "Introduced": "captain_hook.contexts",
    "PromptContext": "captain_hook.contexts",
    "UserMessages": "captain_hook.contexts",
    "WorkflowScriptSource": "captain_hook.contexts",
    "apply_contexts": "captain_hook.contexts",
    "excerpt_around": "captain_hook.contexts",
    "DurableSlot": "captain_hook.durable",
    "DurableState": "captain_hook.durable",
    "DurableStore": "captain_hook.durable",
    "BackgroundTask": "captain_hook.events",
    "BaseHookEvent": "captain_hook.events",
    "NotificationEvent": "captain_hook.events",
    "PermissionRequestEvent": "captain_hook.events",
    "PostToolUseEvent": "captain_hook.events",
    "PostToolUseFailureEvent": "captain_hook.events",
    "PreCompactEvent": "captain_hook.events",
    "PreToolUseEvent": "captain_hook.events",
    "SessionCron": "captain_hook.events",
    "SessionEndEvent": "captain_hook.events",
    "SessionStartEvent": "captain_hook.events",
    "StopEvent": "captain_hook.events",
    "SubagentStartEvent": "captain_hook.events",
    "SubagentStopEvent": "captain_hook.events",
    "ToolHookEvent": "captain_hook.events",
    "ToolRewriteEvent": "captain_hook.events",
    "UserPromptSubmitEvent": "captain_hook.events",
    "Deque": "captain_hook.fields",
    "File": "captain_hook.file",
    "categorize_files": "captain_hook.file",
    "Rewritten": "captain_hook.primitives.commands",
    "WalkContext": "captain_hook.primitives.commands",
    "block_command": "captain_hook.primitives.commands",
    "rewrite_command": "captain_hook.primitives.commands",
    "rewrite_command_occurrences": "captain_hook.primitives.commands",
    "warn_command": "captain_hook.primitives.commands",
    "diff_lint": "captain_hook.primitives.lint",
    "lint": "captain_hook.primitives.lint",
    "GateVerdict": "captain_hook.primitives.llm",
    "NudgeVerdict": "captain_hook.primitives.llm",
    "PromptCheckVerdict": "captain_hook.primitives.llm",
    "llm_gate": "captain_hook.primitives.llm",
    "llm_nudge": "captain_hook.primitives.llm",
    "prompt_check": "captain_hook.primitives.llm",
    "gate": "captain_hook.primitives.nudge",
    "nudge": "captain_hook.primitives.nudge",
    "SafetyVerdict": "captain_hook.primitives.permissions",
    "approve": "captain_hook.primitives.permissions",
    "deny": "captain_hook.primitives.permissions",
    "llm_approve": "captain_hook.primitives.permissions",
    "install_binary": "captain_hook.primitives.provision",
    "rewrite_code": "captain_hook.primitives.rewrite",
    "set_tool_input": "captain_hook.primitives.rewrite",
    "Artifact": "captain_hook.primitives.workflow",
    "Step": "captain_hook.primitives.workflow",
    "Workflow": "captain_hook.primitives.workflow",
    "text_matches": "captain_hook.primitives.workflow",
    "workflow": "captain_hook.primitives.workflow",
    "Prompt": "captain_hook.prompt",
    "SessionSlot": "captain_hook.session",
    "SessionStore": "captain_hook.session",
    "session_state": "captain_hook.session",
    "HooksSettings": "captain_hook.settings",
    "build_settings": "captain_hook.settings",
    "Clause": "captain_hook.signals.nlp",
    "NlpSignal": "captain_hook.signals.nlp",
    "Phrase": "captain_hook.signals.nlp",
    "has_nominal_subject": "captain_hook.signals.nlp",
    "is_past_predicate": "captain_hook.signals.nlp",
    "subject_kind": "captain_hook.signals.nlp",
    "HookState": "captain_hook.state",
    "PrimitiveState": "captain_hook.state",
    "RegisteredTranscript": "captain_hook.state",
    "RegisteredTranscripts": "captain_hook.state",
    "WorkflowState": "captain_hook.state",
    "workflow_state": "captain_hook.state",
    "register_transcript": "captain_hook.transcripts",
    "registered_paths": "captain_hook.transcripts",
    "Task": "captain_hook.tasks",
    "Tasks": "captain_hook.tasks",
    "T": "captain_hook.testing.fixtures",
    "Allow": "captain_hook.testing.types",
    "Turn": "captain_hook.turn",
    "Ask": "captain_hook.testing.types",
    "Block": "captain_hook.testing.types",
    "FileFixture": "captain_hook.testing.types",
    "InlineTests": "captain_hook.testing.types",
    "Input": "captain_hook.testing.types",
    "Rewrite": "captain_hook.testing.types",
    "TranscriptFixture": "captain_hook.testing.types",
    "Warn": "captain_hook.testing.types",
    "Action": "captain_hook.types",
    "Agent": "captain_hook.types",
    "And": "captain_hook.types",
    "Content": "captain_hook.types",
    "CustomCommandLineCondition": "captain_hook.types",
    "CustomCondition": "captain_hook.types",
    "CustomInputTypeCondition": "captain_hook.types",
    "Event": "captain_hook.types",
    "FilePath": "captain_hook.types",
    "FromSubagent": "captain_hook.types",
    "HookResponse": "captain_hook.types",
    "HookResult": "captain_hook.types",
    "InPlanMode": "captain_hook.types",
    "LambdaCondition": "captain_hook.types",
    "Not": "captain_hook.types",
    "Or": "captain_hook.types",
    "Pattern": "captain_hook.types",
    "RanCommand": "captain_hook.types",
    "ReadFile": "captain_hook.types",
    "Runs": "captain_hook.types",
    "Signal": "captain_hook.types",
    "Signals": "captain_hook.types",
    "SkipPermissions": "captain_hook.types",
    "SourceEdits": "captain_hook.types",
    "TCondition": "captain_hook.types",
    "TestFile": "captain_hook.types",
    "Tool": "captain_hook.types",
    "ToolInput": "captain_hook.types",
    "TouchedFile": "captain_hook.types",
    "UsedSkill": "captain_hook.types",
    "UsedTool": "captain_hook.types",
    "Waiting": "captain_hook.types",
    "WorkflowScript": "captain_hook.types",
    "binary_supports": "captain_hook.util.fs",
    "read_json": "captain_hook.util.fs",
    "resolve_binary": "captain_hook.util.fs",
}


def __getattr__(name: str) -> object:
    if name == "__all__":
        globals()[name] = value = sorted(EXPORTS)
        return value
    if (target := EXPORTS.get(name)) is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(target)
    value = module if target == f"{__name__}.{name}" else getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(EXPORTS) | {"__all__"})
