from __future__ import annotations

from captain_hook.command_schema import CommandSchema, Operand, Option

FIND = CommandSchema(
    "find",
    operands=(Operand("roots", count="*", default=(".",)),),
    options=(
        Option("mode", ("-H", "-L", "-P", "-X", "-d", "-s", "-x"), bool, prefix=True),
        Option("roots", ("-f",), prefix=True),
        Option("max_depth", ("-maxdepth",), int),
        Option(
            "predicate",
            (
                "-name",
                "-iname",
                "-path",
                "-ipath",
                "-wholename",
                "-iwholename",
                "-regex",
                "-iregex",
                "-type",
                "-xtype",
                "-mindepth",
                "-mtime",
                "-mmin",
                "-atime",
                "-amin",
                "-ctime",
                "-cmin",
                "-size",
                "-user",
                "-group",
                "-uid",
                "-gid",
                "-perm",
                "-links",
                "-inum",
                "-newer",
                "-fstype",
            ),
        ),
        Option(
            "expression",
            (
                "-a",
                "-and",
                "-o",
                "-or",
                "-not",
                "-print",
                "-print0",
                "-prune",
                "-depth",
                "-xdev",
                "-mount",
                "-empty",
                "-true",
                "-false",
                "-delete",
                "-quit",
                "-ls",
                "-follow",
                "-noleaf",
            ),
            bool,
        ),
        Option("command", ("-exec", "-execdir", "-ok", "-okdir"), until=((";",), ("{}", "+"))),
    ),
    options_end_operands=True,
    separators=("!", "(", ")", ","),
)
