from __future__ import annotations

from captain_hook.cmd import COMMAND_VALUE_FLAGS
from captain_hook.command_schema import CommandSchema, Operand, Option

FIND = CommandSchema(
    "find",
    operands=(Operand("roots", count="*", default=(".",)),),
    options=(
        Option("mode", ("-H", "-L", "-P", "-X", "-d", "-s", "-x"), bool, prefix=True),
        Option("roots", ("-f",), prefix=True),
        Option("max_depth", ("-maxdepth",), int),
        Option(
            "predicate",
            (
                "-name",
                "-iname",
                "-path",
                "-ipath",
                "-wholename",
                "-iwholename",
                "-regex",
                "-iregex",
                "-type",
                "-xtype",
                "-mindepth",
                "-mtime",
                "-mmin",
                "-atime",
                "-amin",
                "-ctime",
                "-cmin",
                "-size",
                "-user",
                "-group",
                "-uid",
                "-gid",
                "-perm",
                "-links",
                "-inum",
                "-newer",
                "-fstype",
            ),
        ),
        Option(
            "expression",
            (
                "-a",
                "-and",
                "-o",
                "-or",
                "-not",
                "-print",
                "-print0",
                "-prune",
                "-depth",
                "-xdev",
                "-mount",
                "-empty",
                "-true",
                "-false",
                "-delete",
                "-quit",
                "-ls",
                "-follow",
                "-noleaf",
            ),
            bool,
        ),
        Option("command", ("-exec", "-execdir", "-ok", "-okdir"), until=((";",), ("{}", "+"))),
    ),
    options_end_operands=True,
    separators=("!", "(", ")", ","),
)

GIT_PUSH = CommandSchema(
    "git",
    operands=(Operand("verb"), Operand("targets", count="*")),
    options=(
        Option("environment", COMMAND_VALUE_FLAGS["git"]),
        Option("force", ("-f", "--force", "--force-with-lease", "--mirror"), bool),
        Option("delete", ("-d", "--delete", "--prune"), bool),
        Option("parameter", ("-o", "--push-option", "--repo", "--receive-pack", "--exec", "--recurse-submodules")),
        Option(
            "mode",
            (
                "-h",
                "--help",
                "-v",
                "--verbose",
                "--version",
                "-q",
                "--quiet",
                "-p",
                "--paginate",
                "-P",
                "--no-pager",
                "--bare",
                "--html-path",
                "--man-path",
                "--info-path",
                "--no-replace-objects",
                "--no-lazy-fetch",
                "--no-optional-locks",
                "--no-advice",
                "--literal-pathspecs",
                "--glob-pathspecs",
                "--noglob-pathspecs",
                "--icase-pathspecs",
                "-n",
                "--dry-run",
                "-u",
                "--set-upstream",
                "-4",
                "--ipv4",
                "-6",
                "--ipv6",
                "--all",
                "--branches",
                "--tags",
                "--follow-tags",
                "--no-follow-tags",
                "--atomic",
                "--no-atomic",
                "--porcelain",
                "--progress",
                "--no-progress",
                "--thin",
                "--no-thin",
                "--signed",
                "--no-signed",
                "--verify",
                "--no-verify",
                "--force-if-includes",
                "--no-force-if-includes",
                "--no-force-with-lease",
                "--no-recurse-submodules",
            ),
            bool,
        ),
    ),
)
