from __future__ import annotations

from captain_hook.cmd import COMMAND_VALUE_FLAGS
from captain_hook.command_schema import CommandSchema, Operand, Option

SIGNAL_NAMES = (
    "HUP",
    "INT",
    "QUIT",
    "ILL",
    "TRAP",
    "ABRT",
    "IOT",
    "EMT",
    "FPE",
    "KILL",
    "BUS",
    "SEGV",
    "SYS",
    "PIPE",
    "ALRM",
    "TERM",
    "URG",
    "STOP",
    "TSTP",
    "CONT",
    "CHLD",
    "CLD",
    "TTIN",
    "TTOU",
    "IO",
    "POLL",
    "XCPU",
    "XFSZ",
    "VTALRM",
    "PROF",
    "WINCH",
    "INFO",
    "USR1",
    "USR2",
    "PWR",
    "STKFLT",
    "RTMIN",
    "RTMAX",
)
SIGNAL_FLAGS = (
    *(f"-{number}" for number in range(1, 65)),
    *(f"-{name}" for name in SIGNAL_NAMES),
    *(f"-SIG{name}" for name in SIGNAL_NAMES),
)

FIND = CommandSchema(
    "find",
    operands=(Operand("roots", count="*", default=(".",)),),
    options=(
        Option("mode", ("-H", "-L", "-P", "-X", "-d", "-s", "-x"), bool, prefix=True),
        Option("roots", ("-f",), prefix=True),
        Option("max_depth", ("-maxdepth",), int),
        Option(
            "predicate",
            (
                "-name",
                "-iname",
                "-path",
                "-ipath",
                "-wholename",
                "-iwholename",
                "-regex",
                "-iregex",
                "-type",
                "-xtype",
                "-mindepth",
                "-mtime",
                "-mmin",
                "-atime",
                "-amin",
                "-ctime",
                "-cmin",
                "-size",
                "-user",
                "-group",
                "-uid",
                "-gid",
                "-perm",
                "-links",
                "-inum",
                "-newer",
                "-fstype",
            ),
        ),
        Option(
            "expression",
            (
                "-a",
                "-and",
                "-o",
                "-or",
                "-not",
                "-print",
                "-print0",
                "-prune",
                "-depth",
                "-xdev",
                "-mount",
                "-empty",
                "-true",
                "-false",
                "-delete",
                "-quit",
                "-ls",
                "-follow",
                "-noleaf",
            ),
            bool,
        ),
        Option("command", ("-exec", "-execdir", "-ok", "-okdir"), until=((";",), ("{}", "+"))),
    ),
    options_end_operands=True,
    separators=("!", "(", ")", ","),
)

GIT_PUSH = CommandSchema(
    "git",
    operands=(Operand("verb"), Operand("targets", count="*")),
    options=(
        Option("environment", COMMAND_VALUE_FLAGS["git"]),
        Option("force", ("-f", "--force", "--force-with-lease", "--mirror"), bool),
        Option("delete", ("-d", "--delete", "--prune"), bool),
        Option("parameter", ("-o", "--push-option", "--repo", "--receive-pack", "--exec", "--recurse-submodules")),
        Option(
            "mode",
            (
                "-h",
                "--help",
                "-v",
                "--verbose",
                "--version",
                "-q",
                "--quiet",
                "-p",
                "--paginate",
                "-P",
                "--no-pager",
                "--bare",
                "--html-path",
                "--man-path",
                "--info-path",
                "--no-replace-objects",
                "--no-lazy-fetch",
                "--no-optional-locks",
                "--no-advice",
                "--literal-pathspecs",
                "--glob-pathspecs",
                "--noglob-pathspecs",
                "--icase-pathspecs",
                "-n",
                "--dry-run",
                "-u",
                "--set-upstream",
                "-4",
                "--ipv4",
                "-6",
                "--ipv6",
                "--all",
                "--branches",
                "--tags",
                "--follow-tags",
                "--no-follow-tags",
                "--atomic",
                "--no-atomic",
                "--porcelain",
                "--progress",
                "--no-progress",
                "--thin",
                "--no-thin",
                "--signed",
                "--no-signed",
                "--verify",
                "--no-verify",
                "--force-if-includes",
                "--no-force-if-includes",
                "--no-force-with-lease",
                "--no-recurse-submodules",
            ),
            bool,
        ),
    ),
)

KILL = CommandSchema(
    "kill",
    operands=(Operand("targets", count="*"),),
    operands_end_options=True,
    options=(
        Option("probe", ("-0",), bool, first=True),
        Option("signal_flag", SIGNAL_FLAGS, bool, first=True),
        Option("signal", ("-s", "-n")),
        Option("list", ("-l", "-L"), bool),
    ),
)

RENICE = CommandSchema(
    "renice",
    operands=(Operand("args", count="*"),),
    options=(
        Option("adjust", ("-n", "--priority", "--relative")),
        Option("pid", ("-p", "--pid"), bool),
        Option("scope", ("-g", "-u", "--pgrp", "--user"), bool),
    ),
)

ORCA = CommandSchema(
    "orca",
    operands=(Operand("group"), Operand("verb"), Operand("rest", count="*")),
    options=(
        Option("help", ("--help", "-h"), bool),
        Option("tab", ("--tab",), bool),
        Option("all", ("--all",), bool),
        Option("interrupt", ("--interrupt",), bool),
        Option(
            "mode",
            (
                "--json",
                "--enter",
                "--force",
                "--run-hooks",
                "--allow-failed-archive-hook",
                "--shell",
                "--inject",
                "--peek",
                "--ack",
                "--screen",
                "--tasks",
                "--messages",
                "--full",
                "--restore-window",
                "--no-screenshot",
            ),
            bool,
        ),
        Option("text_stdin", ("--text-stdin",), bool),
        Option("value_stdin", ("--value-stdin",), bool),
        Option("terminal", ("--terminal",)),
        Option("worktree", ("--worktree",)),
        Option("dispatch", ("--dispatch",)),
        Option("text", ("--text",)),
        Option("value", ("--value",)),
        Option("app", ("--app",)),
        Option("key", ("--key",)),
        Option("action", ("--action",)),
        Option(
            "parameter",
            (
                "--environment",
                "--pairing-code",
                "--command",
                "--limit",
                "--title",
                "--direction",
                "--prompt",
                "--agent",
                "--spec",
                "--to",
                "--run",
                "--for",
                "--retry-request",
                "--wait-submit",
                "--device",
                "--session",
                "--window-id",
                "--window-index",
                "--element-index",
                "--x",
                "--y",
                "--reference",
            ),
        ),
    ),
)

LAUNCHCTL = CommandSchema(
    "launchctl",
    operands=(Operand("verb"), Operand("targets", count="*")),
    options=(
        Option("mode", ("-k", "-p", "-s", "-w", "-F", "-x", "-h"), bool),
        Option("session", ("-S", "-D")),
    ),
)

OSASCRIPT = CommandSchema(
    "osascript",
    operands=(Operand("program", count="*"),),
    options=(
        Option("statement", ("-e",)),
        Option("language", ("-l",)),
        Option("flags", ("-s",)),
        Option("interactive", ("-i",), bool),
    ),
)

SOFTWAREUPDATE = CommandSchema(
    "softwareupdate",
    operands=(Operand("labels", count="*"),),
    options=(
        Option(
            "read",
            (
                "-l",
                "--list",
                "--history",
                "--dump-state",
                "--list-full-installers",
                "--evaluate-products",
                "--no-scan",
                "--verbose",
                "--agree-to-license",
            ),
            bool,
        ),
        Option(
            "mutate",
            (
                "-i",
                "--install",
                "-a",
                "--all",
                "-r",
                "--recommended",
                "--os-only",
                "--safari-only",
                "-R",
                "--restart",
                "--background",
                "--fetch-full-installer",
                "--install-rosetta",
                "-d",
                "--download",
                "--stdinpass",
                "--user",
            ),
            bool,
        ),
    ),
)

PMSET = CommandSchema(
    "pmset",
    operands=(Operand("verb"), Operand("rest", count="*")),
    options=(Option("scope", ("-a", "-b", "-c", "-u", "-g"), bool),),
)

TMUX = CommandSchema(
    "tmux",
    operands=(Operand("verb"), Operand("rest", count="*")),
    options=(
        Option("parameter", ("-S", "-L", "-f", "-c", "-t", "-s", "-n")),
        Option("mode", ("-2", "-C", "-l", "-u", "-v", "-V"), bool),
    ),
)
