# GENERATED by `uv run python hatch_build.py` from internal/wireproto/guard.json.

from __future__ import annotations

import json
import os
import re
import sys
from typing import BinaryIO, cast

EVENTS: frozenset[str] = frozenset({"PreToolUse", "PermissionRequest"})
TOOLS: frozenset[str] = frozenset({"TaskStop"})
QUOTING: str = "[\\\\'\"\\[\\]]"
GUARDED: str = (
    "\\b(kill|pkill|killall|killall5|fuser|skill|snice|kill-port|orca|launchctl|osascript|shutdown|reboot"
    "|halt|poweroff|renice|tmux|softwareupdate|pmset|caffeinate|setsid|builtin|noglob|stdbuf|unbuffer|scr"
    "ipt|watch|parallel|chrt|ionice|taskset|arch|su|chroot|find)\\b"
)
EXEMPT_HEADS: tuple[str, ...] = (
    "cc-slack",
    "ccn",
    "cc-notes",
    "cc-present",
    "cc-transcript",
    "cat",
    "echo",
    "grep",
    "head",
    "jq",
    "tail",
    "wc",
)
FOLDS: dict[str, str] = {"\u0130": "i", "\u0131": "i", "\u017f": "s", "\u212a": "k"}
KINDS: tuple[str, ...] = (
    "host-unavailable",
    "transport-error",
    "transport-timeout",
    "transport-refused",
    "shed",
    "no-verdict",
    "worker-error",
    "dependency-unavailable",
)
NOTE: str = (
    "capt-hook: the session guard did not complete ({kind}), so this call ran without its check for sessi"
    "on-ending programs. Run `capt-hook helper status`, then `capt-hook helper install` if the host is mi"
    "ssing or outdated."
)
MAX_EVENT_INPUT: int = 33554432
PASS_EXIT: int = 3
GUARDED_WORD: re.Pattern[str] = re.compile(GUARDED, re.IGNORECASE | re.ASCII)
QUOTING_CHARS: re.Pattern[str] = re.compile(QUOTING)
FOLD_TABLE: dict[int, str] = str.maketrans(FOLDS)
ASSIGNMENT: re.Pattern[str] = re.compile("^[A-Za-z_][A-Za-z0-9_]*=")
LITERAL_HEAD: re.Pattern[str] = re.compile("[A-Za-z0-9_./~+-]+")
OPAQUE_SHELL: tuple[str, ...] = ("$(", "`", "<(", ">(")
SEGMENT_BREAKS: frozenset[str] = frozenset(";\n|()")
QUOTED_ESCAPES: frozenset[str] = frozenset('$`"\\\n')


def names_guarded(text: str) -> bool:
    return GUARDED_WORD.search(QUOTING_CHARS.sub("", text).translate(FOLD_TABLE)) is not None


# isinstance, not match: the plugin's bin/hook runs this under the first python3 on PATH, stock macOS 3.9 included.
def names_guarded_value(value: object) -> bool:
    if isinstance(value, str):
        return names_guarded(value)
    if isinstance(value, list):
        items = cast(list[object], value)
        words = [item for item in items if isinstance(item, str)]
        return (len(words) == len(items) and names_guarded(" ".join(words))) or any(
            names_guarded_value(item) for item in items
        )
    if isinstance(value, dict):
        return any(names_guarded_value(item) for item in cast(dict[object, object], value).values())
    return False


def first_party_command(tool_input: object) -> bool:
    if not isinstance(tool_input, dict):
        return False
    command = cast(dict[object, object], tool_input).get("command")
    if not isinstance(command, str):
        return False
    joined = command.replace("\\\n", "")
    if any(opaque in joined for opaque in OPAQUE_SHELL):
        return False
    segments = shell_segments(command)
    return segments is not None and all(exempt_segment(words) for words in segments)


def exempt_segment(words: list[tuple[str, str, bool]]) -> bool:
    for raw, cooked, redirect in words:
        if redirect:
            return False
        if ASSIGNMENT.match(raw) is None:
            return LITERAL_HEAD.fullmatch(cooked) is not None and cooked.rpartition("/")[2] in EXEMPT_HEADS
    return True


def shell_segments(command: str) -> list[list[tuple[str, str, bool]]] | None:
    segments: list[list[tuple[str, str, bool]]] = [[]]
    raw: list[str] = []
    cooked: list[str] = []
    started = redirect = after_redirect = False

    def end_word() -> None:
        nonlocal started, redirect
        if started:
            segments[-1].append(("".join(raw), "".join(cooked), redirect))
        raw.clear()
        cooked.clear()
        started = redirect = False

    index = 0
    while index < len(command):
        char = command[index]
        redirecting = False
        if char == "\\" and index + 1 == len(command):
            raw.append(char)
            cooked.append(char)
            started = True
        elif char == "\\":
            index += 1
            if command[index] != "\n":
                raw.append(command[index - 1 : index + 1])
                cooked.append(command[index])
                started = True
        elif char == "'":
            end = command.find("'", index + 1)
            if end < 0:
                return None
            raw.append(command[index : end + 1])
            cooked.append(command[index + 1 : end])
            started = True
            index = end
        elif char == '"':
            end = index + 1
            while end < len(command) and command[end] != '"':
                escaped = command[end] == "\\" and end + 1 < len(command) and command[end + 1] in QUOTED_ESCAPES
                end += escaped
                if not (escaped and command[end] == "\n"):
                    cooked.append(command[end])
                end += 1
            if end == len(command):
                return None
            raw.append(command[index : end + 1])
            started = True
            index = end
        elif char in " \t":
            end_word()
        elif char in SEGMENT_BREAKS or (char == "&" and not after_redirect and command[index + 1 : index + 2] != ">"):
            end_word()
            segments.append([])
        else:
            raw.append(char)
            cooked.append(char)
            started = True
            redirecting = char in "<>"
            redirect = redirect or redirecting
        after_redirect = redirecting
        index += 1
    end_word()
    return segments


def mandatory(event: str, payload: bytes) -> bool:
    if event not in EVENTS:
        return False
    try:
        fields = json.loads(payload.decode(errors="replace"))
    except ValueError:
        return False
    if not isinstance(fields, dict):
        return False
    payload_fields = cast(dict[object, object], fields)
    tool = payload_fields.get("tool_name")
    if isinstance(tool, str) and tool in TOOLS:
        return True
    if tool == "Bash" and first_party_command(payload_fields.get("tool_input")):
        return False
    return names_guarded_value(tool) or names_guarded_value(payload_fields.get("tool_input"))


def skip_envelope(event: str, kind: str) -> str:
    if kind not in KINDS:
        raise ValueError(f"unknown guard kind {kind!r}")
    note = NOTE.replace("{kind}", kind)
    output: dict[str, object] = {"systemMessage": note}
    if event != "PermissionRequest":
        output["hookSpecificOutput"] = {"hookEventName": event, "additionalContext": note}
    return json.dumps(output, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def skip_if_mandatory(event: str, stdin: BinaryIO, *, prefix: bytes = b"") -> int:
    if event not in EVENTS or not mandatory(event, prefix + stdin.read(MAX_EVENT_INPUT + 1)):
        return PASS_EXIT
    print(skip_envelope(event, "host-unavailable"))
    return 0


# bin/hook has read one byte of stdin to tell a refused resolver from a host that spent the payload; argv[2] carries it.
if __name__ == "__main__":
    raise SystemExit(skip_if_mandatory(sys.argv[1], sys.stdin.buffer, prefix=os.fsencode(sys.argv[2])))
