# GENERATED by `uv run python hatch_build.py` from internal/wireproto/guard.json.

from __future__ import annotations

import json
import os
import re
import sys
from typing import BinaryIO, cast

EVENTS: frozenset[str] = frozenset({"PreToolUse", "PermissionRequest"})
QUOTING: str = "[\\\\'\"\\[\\]]"
GUARDED: str = (
    "\\b(kill|pkill|killall|killall5|fuser|skill|snice|kill-port|orca|launchctl|osascript|shutdown|reboot"
    "|halt|poweroff|renice|tmux|softwareupdate|pmset|caffeinate|setsid|builtin|noglob|stdbuf|unbuffer|scr"
    "ipt|watch|parallel|chrt|ionice|taskset|arch|su|chroot|find)\\b"
)
FOLDS: dict[str, str] = {"\u0130": "i", "\u0131": "i", "\u017f": "s", "\u212a": "k"}
KINDS: tuple[str, ...] = (
    "host-unavailable",
    "transport-error",
    "transport-timeout",
    "transport-refused",
    "shed",
    "no-verdict",
    "worker-error",
    "dependency-unavailable",
)
REASON: str = (
    "BLOCKED: the session guard did not complete ({kind}), so this call could not be checked for a sessio"
    "n-ending program and stays denied (AGENTS.md § Protect Existing Sessions). Retry once the Captain Ho"
    "ok host answers, or ask the owner to install the host or run the call themselves."
)
MAX_EVENT_INPUT: int = 33554432
PASS_EXIT: int = 3
GUARDED_WORD: re.Pattern[str] = re.compile(GUARDED, re.IGNORECASE | re.ASCII)
QUOTING_CHARS: re.Pattern[str] = re.compile(QUOTING)
FOLD_TABLE: dict[int, str] = str.maketrans(FOLDS)


def names_guarded(text: str) -> bool:
    return GUARDED_WORD.search(QUOTING_CHARS.sub("", text).translate(FOLD_TABLE)) is not None


# isinstance, not match: the plugin's bin/hook runs this under the first python3 on PATH, stock macOS 3.9 included.
def names_guarded_value(value: object) -> bool:
    if isinstance(value, str):
        return names_guarded(value)
    if isinstance(value, list):
        items = cast(list[object], value)
        words = [item for item in items if isinstance(item, str)]
        return (len(words) == len(items) and names_guarded(" ".join(words))) or any(
            names_guarded_value(item) for item in items
        )
    if isinstance(value, dict):
        return any(names_guarded_value(item) for item in cast(dict[object, object], value).values())
    return False


def mandatory(event: str, payload: bytes) -> bool:
    if event not in EVENTS:
        return False
    try:
        fields = json.loads(payload.decode(errors="replace"))
    except ValueError:
        return False
    if not isinstance(fields, dict):
        return False
    payload_fields = cast(dict[object, object], fields)
    return names_guarded_value(payload_fields.get("tool_name")) or names_guarded_value(payload_fields.get("tool_input"))


def deny_envelope(event: str, kind: str) -> str:
    if kind not in KINDS:
        raise ValueError(f"unknown guard kind {kind!r}")
    reason = REASON.replace("{kind}", kind)
    output = (
        {"hookEventName": event, "decision": {"behavior": "deny", "message": reason}}
        if event == "PermissionRequest"
        else {"hookEventName": event, "permissionDecision": "deny", "permissionDecisionReason": reason}
    )
    return json.dumps({"hookSpecificOutput": output}, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def deny_if_mandatory(event: str, stdin: BinaryIO, *, prefix: bytes = b"") -> int:
    if event not in EVENTS or not mandatory(event, prefix + stdin.read(MAX_EVENT_INPUT + 1)):
        return PASS_EXIT
    print(deny_envelope(event, "host-unavailable"))
    return 0


# bin/hook has read one byte of stdin to tell a refused resolver from a host that spent the payload; argv[2] carries it.
if __name__ == "__main__":
    raise SystemExit(deny_if_mandatory(sys.argv[1], sys.stdin.buffer, prefix=os.fsencode(sys.argv[2])))
