# GENERATED by `uv run python hatch_build.py` from internal/wireproto/resource.json.

from __future__ import annotations

ENV_PREFIX: str = "HOOKS_PERFORMANCE_"
DEFAULTS: dict[str, bool | int | float] = {
    "enabled": True,
    "sample_interval_seconds": 15,
    "min_runtime_seconds": 120,
    "cpu_fraction": 0.5,
    "sustain_seconds": 60,
    "disk_bytes_per_second": 52428800,
    "grace_seconds": 60,
    "escalate_after_seconds": 30,
    "max_tracked_per_session": 32,
    "registry_cap": 512,
}
